name: Alpha
description: Alphs template for Jekyll
baseurl: ''

url: ""

paginate: 5
gems: [jekyll-paginate]


highlighter: rouge

excerpt_separator: "\n"

owner:
  name:           Ying Huang (Inger)
