name: Alpha
description: Alphs template for Jekyll
baseurl: ''

url: ""

paginate: 5
gems: [jekyll-paginate]


highlighter: pygments

excerpt_separator: "\n"

permalink: /:title

owner:
  name:           Ying Huang (Inger)


markdown: redcarpet

redcarpet:
    extensions: [ "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "prettify","no_intra_emphasis"]
